### ISSUE TITLE
Error 404: https://blog.appknox.com/the-ultimate-security-checklist-while-launching-your-mobile-app/

### ISSUE THREAD

**Issue by mohitmamoria** [xysec/appknox.com#25]

**Comment by dhilipsiva** [comment]
@mohitmamoria Thanks for bringing this to our attention. We will look into this as soon as possible.

**Comment by subho007** [comment]
@mohitmamoria can you tell me which link led you to this link, as far as I have checked we have two blog posts:
1. Ultimate Checklist for Android App: https://blog.appknox.com/the-ultimate-security-checklist-while-launching-your-android-app/
2. Ultimate Checklist for iOS App: https://blog.appknox.com/the-ultimate-security-checklist-while-launching-your-android-app/

**Comment by mohitmamoria** [comment]
The first sentence in the iOS post (
https://blog.appknox.com/the-ultimate-security-checklist-while-launching-your-ios-app/)
led me to this broken page. :)

I hope this works. Thanks for promptly directing me to the right link.
- Mohit :)

**Comment by subho007** [comment]
Thanks @mohitmamoria this has been fixed ! :+1:

**Comment by mohitmamoria** [comment]
Awesome. :)
- Mohit :)
